# Generated by Django 3.1.7 on 2021-05-14 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aadmi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now=True)),
                ('advisor_name', models.CharField(max_length=20)),
                ('advisor_image', models.ImageField(upload_to='bookimages')),
                ('khiladi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aadmi', to='main.main')),
            ],
        ),
    ]
